### PR TITLE
Use dirname(@__FILE__) instead of Pkg.dir, modernize Travis, and fix up REQUIRE

### PR DESCRIPTION
**Pull request by tkelman**
See commit messages

### CODE REVIEW

**Comment by jzuhone** [comment]
The test failure is a bit odd, can't find the dataset. Hoping it's a one-off fluke, so I hit it again.

**Comment by jzuhone** [comment]
Not sure why the test is failing. Have you tried to reproduce the failure on your end?

**Comment by tkelman** [comment]
No I haven't, this was one of a big batch of many pull requests. Let's see if restarting gives a different result this time.

**Comment by jzuhone** [comment]
@tkelman it appears that the issue is that the location that the tests are being run from relative to the location of the downloaded files got moved somehow in your code change, so it can't find the `enzo_tiny_cosmology` file or anything else it downloaded to use as test datasets. Can you check the working directory that the tests get run from?

**Comment by tkelman** [comment]
Oh, it gets run from the package directory. You should handle the downloading of the test data in your `runtests.jl` julia script so users could actually run `Pkg.test("YT")`, rather than only ever working on Travis.

**Comment by jzuhone** [comment]
@tkelman care to change `runtests.jl` so it downloads test data from within this PR? I'd be happy to see this merged in.

**Comment by tkelman** [comment]
Guess I could take a look sometime later. Wish github had a "mark notification as unread" option

**Comment by jzuhone** [comment]
@tkelman I could try doing something about it--I haven't quite figured out how to use this new feature where you can add to someone's PR yet. I think it should go into this PR though.

Sorry about the delay on this--million balls in the air over here. I'll look into it tomorrow. 

I'm very happy that someone's getting some use out of this code.

**Comment by tkelman** [comment]
I just checked the box that allows you to edit the branch. I've also got a lot going on, no hurry.

**Comment by jzuhone** [comment]
I just submitted https://github.com/tkelman/YT.jl/pull/1, which should hopefully make the tests pass.

**Comment by tkelman** [comment]
Would be more portable to use Base.download and Libz.jl, but better than nothing

**Comment by jzuhone** [comment]
Yeah, maybe I can try that after we merge this in. Tests are only going to pass for v4.x, but we shouldn't try to fix that in here.

**Comment by jzuhone** [comment]
Tests passed on v0.4.x, failed on v0.5.x, which is what I expected, so I'm going to merge this in and try to make things compatible with both (and nightly) this week.

Thanks, @tkelman!

**Pull request merged**
